### ISSUE TITLE
Firefox - can't open Dollchan setting menu

### ISSUE THREAD

**Issue by BondiBear** [SthephanShinkufag/Dollchan-Extension-Tools#1138]
FF57 64, Tampermonkey 4.5.55.90, Dollchan 17.10.24.0

Can no longer access the Dollchan settings menu (gear icon). 
Clicking on the icon does not open the options menu. Alt-s also does not open the options menu.

The only time it works is if I reinstall Dollchan, then I can access the settings menu ONE TIME. 
Then when the tab is reloaded, the problem is back.

This affects Krautchan and 8chan (and probably all sites).

**Comment by WagonOfDoubt** [comment]
As temporary solution, try not to use spells (uncheck checkbox and delete all contents).
This issue is related to #1107. There was similar problem on one imageboard.
This bug now also appears in Chrome.

**Comment by SthephanShinkufag** [comment]
*  Install the [latest version of the script](https://raw.github.com/SthephanShinkufag/Dollchan-Extension-Tools/master/Dollchan_Extension_Tools.user.js)
* Click `Settings window` > `Reset...` button and clear all settings. Don't forget to backup your settings (by `File` button).

Is there still a problem?

**Comment by BondiBear** [comment]
Did not help. Still the same problem, sorry.

**Comment by SthephanShinkufag** [comment]
Did you have another extensions except Tampermonkey? Adblockers, etc.
Try to disable them all.

**Comment by BondiBear** [comment]
Turned off all extensions except Tampermonkey, but the problem is still there.

**Comment by SthephanShinkufag** [comment]
What is written in the error console `(Ctrl+Shift+J)` after the trying to call Settnigs window?

**Comment by BondiBear** [comment]
_Loading failed for the <script> with source “https://krautchan.net/js/scriptaculous/effects.js”.  thread-12746605.html:18
Error: WebExtension context not found!  ExtensionParent.jsm:821:13
Invalid chrome URI: /
TypeError: parent is null  thread-12746605.html:927:7_

**Comment by BondiBear** [comment]
Update: trying to click on the settings/gear icon causes the page to scroll to the top (as if you were to hit the 'home' key on your keyboard). The settings menu still cannot be accessed.

**Comment by SthephanShinkufag** [comment]
Finally I got that bug. Seems it's the same problem as #1107

**Comment by SthephanShinkufag** [comment]
@BondiBear 

Done. Please clear your settings, then install the fixed script:

https://raw.github.com/SthephanShinkufag/Dollchan-Extension-Tools/master/Dollchan_Extension_Tools.user.js

**Comment by BondiBear** [comment]
I have tried what you requested, but the problem remains unchanged, sorry.

**Comment by SthephanShinkufag** [comment]
It's impossible. Maybe you do it wrong.
Go to any **working** imageboard, call `"Settings" window` - `"File" button` - check "Settings for all domains", and click `"Get the file"`.
Show me that file (inb4 deanon).

**Comment by BondiBear** [comment]
Hello, I have now tried **all** the image boards here [https://github.com/sthephanshinkufag/dollchan-extension-tools/wiki/supported-en](url).

I cannot open the Dollchan settings in any of them.

What I also tried was completely uninstalling Dollchan, then freshly installing from the link you gave me into Tampermonkey, but this made no difference.

Notes: The version showing now is 18.1.4.0. Also, I can no longer access the Dollchan settings even after the first fresh install, which was possible as I described earlier in this thread.

**Comment by SthephanShinkufag** [comment]
`GM` settings must be completely cleared when you delete the script by clicking of the "Recycle bin" icon of Tampermonkey's panel. Hence, your bug generally have nothing to do with dollchan's settings. You have some other different  problem than #1107.
Once the behavior has changed, could you once again to do the following:

* Go to any board with your bug
* Open the error console by `Ctrl+Shift+J`
* Clear the console by clicking ot the "Recycle bin" icon
* Call the settings by clicking on the gear icon of script panel.
* Copy the errors here if they occur.

**Comment by BondiBear** [comment]
Note: Clicking the gear icon scrolls the page to the top. Command alt-s opens the Firefox history menu, maybe conflict there.

This is all the can be found clicking the gear icon:

_Error: Promised response from onMessage listener at u</<.value</<@moz-extension://5c108050-5c42-4ce9-a41a-90818de2a8fe/dist/background.js:20:419595 went out of scope  undefined
file:///C:/Users/XXX/AppData/Roaming/Mozilla/Firefox/Profiles/xxxww63r.default/lwtheme/lightweighttheme-header-1920x1080?563432;1.0
file:///C:/Users/XXX/AppData/Roaming/Mozilla/Firefox/Profiles/xxxww63r.default/lwtheme/lightweighttheme-header-1920x1080?563432;1.0
file:///C:/Users/XXX/AppData/Roaming/Mozilla/Firefox/Profiles/xxxww63r.default/lwtheme/lightweighttheme-footer-1920x1080?563432;1.0
Error: Promised response from onMessage listener at u</<.value</<@moz-extension://5c108050-5c42-4ce9-a41a-90818de2a8fe/dist/background.js:20:419595 went out of scope  undefined_

**Comment by SthephanShinkufag** [comment]
I did not ask you to press alt+s. I do not care about the scroll information, it does not matter.

Is these errors appear **at the moment of clicking** on the icon with the gear?
.

**Comment by SthephanShinkufag** [comment]
Because these errors are not related to dollchan script.

**Comment by BondiBear** [comment]
Nothing else appears when clicking gear icon, no.

**Comment by SthephanShinkufag** [comment]
> @moz-extension://5c108050-5c42-4ce9-a41a-90818de2a8fe

I would like to know what kind of extension it is... Google search on this id does not give anything.

So, please try the following:

- Uninstall Tampermonkey
- Go to `C:\Users\XXX\AppData\Roaming\Mozilla\Firefox\Profiles\xxxww63r.default\browser-extension-data` and delete `firefox@tampermonkey.net` folder if it exists.
- Install Tampermonkey again

If this does not help, try to install [Violentmonkey](https://addons.mozilla.org/en-US/firefox/addon/violentmonkey/) instead of Tampermonkey.

Please tell me about results.
And thank you for your efforts. We will force Dollchan to work sooner or later =)

**Comment by BondiBear** [comment]
Did as you asked:
- Tampermonkey: still doesn't work.
- Violentmonkey: has the **same** problem as TM. No access to settings.
- Greasemonkey: impossible to install DC because of alleged Firefox **_bug Warning: A Firefox bug prevents user script installation from some sites, including Github and Gist, from working as intended._** 

Looks like everything's f%$ked, and I just have to live with the problem for now. :(

**Comment by SthephanShinkufag** [comment]
@BondiBear 

Please type `about:support` in the address bar. Search for "Extensions" table, like this:

![about support extensions](https://user-images.githubusercontent.com/1059874/34673938-ab0db072-f48c-11e7-9381-e859f0b61a4c.png)

Show it for me. I really want to know what is `{5c108050-5c42-4ce9-a41a-90818de2a8fe}` addon.

> Error: Promised response from onMessage listener at u</<.value</<@moz-extension://5c108050-5c42-4ce9-a41a-90818de2a8fe/dist/background.js:20:419595 went out of scope undefined

It is possible that this addon conflicts with Dollchan.
Are you sure that all the add-ons except Tampermonkey have been disabled?
Try to disable that addon at least.

Also,
> file:///C:/Users/XXX/AppData/Roaming/Mozilla/Firefox/Profiles/xxxww63r.default/lwtheme/lightweighttheme-footer-1920x1080?563432;1.0

disable that `lightweighttheme`.  Try to select the default Firefox theme.

**Comment by BondiBear** [comment]
here is the about:support data
![extensions](https://user-images.githubusercontent.com/2057221/34676744-2c9ce274-f48e-11e7-9c43-06035213492a.PNG)
It's not in this list, but files for it exist in _AppData\Roaming\Mozilla\Firefox\Profiles\xxxx63r.default\storage\default_
![moz](https://user-images.githubusercontent.com/2057221/34677595-f26f3c7a-f490-11e7-9220-df64fcdbcda2.PNG)

Resetting to default theme did not help. 
I also disabled all addons and activated them one-by-one.
After I got to an extension called _**tap-to-tab**_, the options menu appeared again!
But soon after, the problem was back, even with **_tap-to-tab_** being disabled -> the error is not consistent.

**Comment by SthephanShinkufag** [comment]
As I expected.

Most likely, you have several conflicting applications, not just `tap-to-tab`.
Try to create a clean Firefox profile, do not install any add-ons at all.
I'm more than confident that everything will work on a clean profile.

**Comment by SthephanShinkufag** [comment]
Instead of creating the clean profile you can download portable Firefox:

https://portableapps.com/apps/internet/firefox_portable

Install Tampermonkey and Dollchan here, and nothing more.

**Comment by BondiBear** [comment]
I believe I have fixed it:

The first issue came from corrupted Dollchan settings.
I created another Firefox profile, set my scripts up and copied the new **tampermonkey storage.js** into my old profile. And it works!

Secondly, the addon **tap-to-tab** must be disabled in order to access the Dollchan settings, but it seems to work!

Hopefully this will continue to work. Thanks for your help. :)

**Comment by SthephanShinkufag** [comment]
Good news.
Congratulations!
